name: PitSimBungee
description: Manages the proxy of the PitSim network
main: net.pitsim.bungee.BungeeMain
version: 1.0
author: PitSim
depends: [PitSimBungeeDependencies, LuckPerms, PluginQuery]
commands:
  play:
  toggle:
  dev: